source 'https://rubygems.org'

# ruby '1.9.3'

gem 'rails', '3.2.13'
gem 'json', '~> 1.7.7'
gem 'dalli'

group :development do
  gem 'pry-rails'
  gem 'thin'
  # gem 'unicorn'
  # gem 'puma'
end

group :production do
  #gem 'unicorn'
  #gem 'pg'
end

platforms :ruby do
  gem 'sqlite3'
end

platforms :jruby do
  gem 'jruby-openssl'
  gem 'activerecord-jdbcsqlite3-adapter'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'shoulda'
end

# jQuery
gem 'jquery-rails'

# Kickstarter's awesome Amazon Flexible Payments gem
gem 'amazon_flex_pay'

# Configuration File
gem 'rails_config'
